version: '3.8'

services:
  base:
    build:
      context:
        .
    hostname: api
    container_name: tcsbase
    entrypoint: python
    command: main.py
    # ports:
    #   - "5001:5001"

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A update:celery worker --loglevel=INFO
    volumes:
      - .:/app

  beat:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A update:celery beat --loglevel=INFO
    volumes:
      - .:/app
